//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASTERIX.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASTERIX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///LIGHT AIRCRAFT
        ///SMALL AIRCRAFT
        ///MEDIUM AIRCRAFT
        ///HIGH VORTEX LARGE
        ///HEAVY AIRCRAFT
        ///HIGHLY MANOEUVRABLE AND HIGH SPEED
        ///
        ///
        ///
        ///ROTOCRAFT
        ///GLIDER / SAILPLANE
        ///LIGHTER-THEN-AIR
        ///UNMANNED AERIAL VEHICLE
        ///SPACE / TRANSATMOSPHERIC VEHICLE
        ///ULTRALIGHT / HANDGLIDER / PARAGLIDER
        ///PARACHUTIST / SKYDIVER
        ///
        ///
        ///
        ///SURFACE EMERGENCY VEHICLE
        ///SURFACE SERVICE VEHICLE
        ///FIXED GROUND OR TETHERED OBSTRUCTION
        ///CLUSTER OBSTACLE
        ///LINE OBSTACLE.
        /// </summary>
        internal static string Emitter_Category {
            get {
                return ResourceManager.GetString("Emitter_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mouseenterStart {
            get {
                object obj = ResourceManager.GetObject("mouseenterStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mouseenterStop {
            get {
                object obj = ResourceManager.GetObject("mouseenterStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @
        ///A
        ///B
        ///C
        ///D
        ///E
        ///F
        ///G
        ///H
        ///I
        ///J
        ///K
        ///L
        ///M
        ///N
        ///O
        ///P
        ///Q
        ///R
        ///S
        ///T
        ///U
        ///V
        ///W
        ///X
        ///Y
        ///Z
        ///[
        ///\
        ///]
        ///^
        ///_
        ///
        ///!
        ///&quot;
        ///#
        ///$
        ///%
        ///&amp;
        ///&apos;
        ///(
        ///)
        ///*
        ///+
        ///,
        ///-
        ///.
        ////
        ///0
        ///1
        ///2
        ///3
        ///4
        ///5
        ///6
        ///7
        ///8
        ///9
        ///:
        ///;
        ///&lt;
        ///=
        ///&gt;
        ///?.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
    }
}
